name: Update Badges

on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run quality checks and generate badges
      id: badges
      run: |
        # Get workflow status
        WORKFLOW_STATUS="${{ github.event.workflow_run.conclusion }}"
        
        # Run actual checks
        echo "Running PHP 7.4 compatibility check..."
        if vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 7.4- src/ roko.php > /dev/null 2>&1; then
          PHP74_STATUS="passing"
          PHP74_COLOR="brightgreen"
        else
          PHP74_STATUS="failing" 
          PHP74_COLOR="red"
        fi
        
        echo "Running WordPress coding standards check..."
        if vendor/bin/phpcs --standard=WordPress src/ roko.php > /dev/null 2>&1; then
          WPCS_STATUS="passing"
          WPCS_COLOR="brightgreen"
        else
          WPCS_STATUS="failing"
          WPCS_COLOR="red"
        fi
        
        # Build status
        if [ "$WORKFLOW_STATUS" = "success" ]; then
          BUILD_STATUS="passing"
          BUILD_COLOR="brightgreen"
        else
          BUILD_STATUS="failing"
          BUILD_COLOR="red"
        fi
        
        # Create badge JSON files for shields.io endpoint
        mkdir -p .github/badges
        
        # Build badge
        cat > .github/badges/build.json << EOF
        {
          "schemaVersion": 1,
          "label": "build",
          "message": "$BUILD_STATUS",
          "color": "$BUILD_COLOR"
        }
        EOF
        
        # PHP 7.4 badge
        cat > .github/badges/php74.json << EOF
        {
          "schemaVersion": 1,
          "label": "PHP 7.4",
          "message": "$PHP74_STATUS",
          "color": "$PHP74_COLOR"
        }
        EOF
        
        # WPCS badge
        cat > .github/badges/wpcs.json << EOF
        {
          "schemaVersion": 1,
          "label": "coding standards",
          "message": "$WPCS_STATUS", 
          "color": "$WPCS_COLOR"
        }
        EOF
        
        echo "Generated badge files:"
        ls -la .github/badges/

    - name: Update README with dynamic badges
      run: |
        # Use shields.io with GitHub raw URLs for dynamic badges
        REPO="JosephGabito/roko"
        BRANCH="main"
        
        NEW_BADGES="[![Build Status](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/$REPO/$BRANCH/.github/badges/build.json)](https://github.com/$REPO/actions/workflows/code-quality.yml)
        [![PHP 7.4 Compatibility](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/$REPO/$BRANCH/.github/badges/php74.json)](https://github.com/$REPO/actions/workflows/code-quality.yml)
        [![Coding Standards](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/$REPO/$BRANCH/.github/badges/wpcs.json)](https://github.com/$REPO/actions/workflows/code-quality.yml)
        [![Last Commit](https://img.shields.io/github/last-commit/$REPO)](https://github.com/$REPO/commits/main)"
        
        if [ -f "README.md" ] && grep -q "<!-- BADGES-START -->" README.md; then
          awk -v badges="$NEW_BADGES" '
            /<!-- BADGES-START -->/ {
              print
              print badges
              while (getline > 0 && !/<!-- BADGES-END -->/) continue
              print "<!-- BADGES-END -->"
              next
            }
            { print }
          ' README.md > README.tmp && mv README.tmp README.md
        fi

    - name: Commit badge updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add .github/badges/ README.md
        if ! git diff --cached --quiet; then
          git commit -m "Update dynamic badges [skip ci]"
          git push
        fi 